/**
 * @module SharedLock
 */

import { type IEventListenable } from "@/event-bus/contracts/_module.js";
import { type ISharedLock } from "@/shared-lock/contracts/shared-lock.contract.js";
import { type SharedLockEventMap } from "@/shared-lock/contracts/shared-lock.events.js";
import { type ITimeSpan } from "@/time-span/contracts/_module.js";

/**
 * The `ISharedLockListenable` contract defines a way for listening {@link ISharedLock | `ISharedLock`} operations.
 *
 * IMPORT_PATH: `"@daiso-tech/core/shared-lock/contracts"`
 * @group Contracts
 */
export type ISharedLockListenable = IEventListenable<SharedLockEventMap>;

/**
 * IMPORT_PATH: `"@daiso-tech/core/shared-lock/contracts"`
 * @group Contracts
 */
export type SharedLockFactoryCreateSettings = {
    limit: number;

    /**
     * You can also provide a `settings.ttl` value using. If not specified it defaults to null, meaning no TTL is applied.
     */
    ttl?: ITimeSpan | null;

    /**
     * You can provide a custom lock id. If not specified a unique lock id will be generated by default.
     */
    lockId?: string;
};

/**
 * IMPORT_PATH: `"@daiso-tech/core/shared-lock/contracts"`
 * @group Contracts
 */
export type ISharedLockFactoryBase = {
    /**
     * The `create` method is used to create an instance of {@link ISharedLock | `ISharedLock`}.
     */
    create(key: string, settings: SharedLockFactoryCreateSettings): ISharedLock;
};

/**
 * The `ISharedLockFactory` contract defines a way for managing locks independent of the underlying technology.
 * It comes with more convenient methods compared to `ISharedLockAdapter`.
 *
 * IMPORT_PATH: `"@daiso-tech/core/shared-lock/contracts"`
 * @group Contracts
 */
export type ISharedLockFactory = ISharedLockFactoryBase & {
    readonly events: ISharedLockListenable;
};
